# Generated by Django 2.2.4 on 2023-06-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_many', '0002_book_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
    ]
